# As instructed by get-started part 3 Docker tutorial; kinda a deployment instruction of how 1 image should be deployed as a service of 1-n containers...
version: "3"
services:
  web: # a service called web
    # replace username/repo:tag with your name and image details
    # pull this image from the 'registry'
    image: mdeselincourt/get-started:part2
    deploy:
        # run 6 instances in web
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports: # map port 4000 on the host to port 40. 
      - "4000:80"
    networks: # this is a load-balanced network, I guess how you can have 5 "port 80s"
      - webnet
networks:
    # "define webnet with default settings which is a load-balanced overlay network" (?)
  webnet: